# Generated by Django 4.2.1 on 2023-07-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Producto'),
        ),
    ]
