# Generated by Django 4.2.1 on 2023-07-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idproducto',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='ID Producto'),
        ),
    ]
